version: "3.8"
services:
  db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
        - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
