
GET http://localhost:3000/cliente/1
###

GET http://localhost:3000/cliente

###
POST http://localhost:3000/cliente
Content-Type: application/json

{
  "limite": "10000",
  "saldoInicial": "10000"
}

###


POST http://localhost:3000/cliente/1/transacoes
Content-Type: application/json

{
  "valor": 21,
  "tipo": "c",
  "descricao": "zezin do queijo"
}

###

GET http://localhost:3000/cliente/6/extrato